### ISSUE TITLE
Attributes sort order

### ISSUE THREAD

**Issue by HunteX** [TinkoffCreditSystems/linters#13]
### 🚀 Feature request
Attributes sort order
---

### Description
```
*attr
#attr
attr
[attr]
[(attr)]
(attr)
```

### Example
```
<div
    *ngIf="predicate"
    #block
    class="classname"
    [model]="model"
    (click)="onClick()"
></div>
```

**Comment by SuperOleg39** [comment]
Hi!

Looks like this [rule proposal](https://github.com/angular-eslint/angular-eslint/issues/127) in `anbular-eslint` can help with attributes sorting?

**Comment by splincode** [comment]
released: https://github.com/TinkoffCreditSystems/linters/blob/master/packages/prettier-config/angular.js#L14
